### ISSUE TITLE
content visibility on smaller screens

### ISSUE THREAD

**Issue by laeubli** [venyz/Terminology#1]
Due to the relatively large size of the header section, only ~10 actual content items are visible when accessing TTC with a small to mid-sized screen/resolution. Reducing the spacing between the header and content sections might improve usability.

![screenshot](https://cloud.githubusercontent.com/assets/4609749/4011002/67d288fc-29fe-11e4-9c55-8fc52051da26.png)

**Comment by venyz** [comment]
Fixed by reducing header margin.
